name: clone workflow
on:
  workflow_dispatch:
jobs:
  clone:
    name: Clone
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo into host
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
              touch ~/.ssh/known_hosts
              ssh-keyscan -H github.com >> ~/.ssh/known_hosts
              cd /pub/zteselko
              git clone git@github.com:zacht9/cmsc389T-web-template.git

